name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: v22
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Update npm
        run: npm install -g npm@latest

      - run: pnpm i

      - name: Prepare
        run: pnpm run dev:prepare

      - name: PNPM build
        run: pnpm run prepack

      - name: Publish to NPM
        run: pnpm publish --access public --no-git-checks
