name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.23.2
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Update npm
        run: npm install -g npm@latest

      - run: pnpm i

      - name: Prepare
        run: pnpm run dev:prepare

      - name: PNPM build
        run: pnpm run prepack

      - name: Publish to NPM
        run: pnpm publish --access public --no-git-checks
