name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: v18
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i

      - name: Prepare
        run: pnpm run dev:prepare

      - name: PNPM build
        run: pnpm run prepack

      - name: Publish to NPM
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
